org: gfc0r
service: api-productos-categorias

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::570699102669:role/LabRole

  environment:
    PRODUCTS_TABLE:   ${sls:stage}-t_productos     
    CATEGORIES_TABLE: ${sls:stage}-t_categorias    
    JWT_SECRET: "tu_clave_secreta_super_segura"
    VERIFY_TOKEN_URL: https://7q0ekap8l8.execute-api.us-east-1.amazonaws.com/dev/usuarios/verify

functions:
  crearProducto:
    handler: create_product.lambda_handler
    package:
      include:
        - create_product.py
    events:
      - http:
          path: /productos/crear
          method: post
          cors: true

  eliminarProducto:
    handler: delete_product.lambda_handler
    package:
      include:
        - delete_product.py
    events:
      - http:
          path: /productos/eliminar
          method: delete
          cors: true

  modificarProducto:
    handler: update_product.lambda_handler
    package:
      include:
        - update_product.py
    events:
      - http:
          path: /productos/modificar
          method: put
          cors: true

  obtenerProducto:
    handler: get_product_by_id.lambda_handler
    package:
      include:
        - get_product_by_id.py
    events:
      - http:
          path: /productos/obtener
          method: get
          cors: true

  listarProductos:
    handler: list_products.lambda_handler
    package:
      include:
        - list_products.py
    events:
      - http:
          path: /productos/listar
          method: get
          cors: true

  listarProductosCategoria:
    handler: list_products_by_category.lambda_handler
    package:
      include:
        - list_products_by_category.py
    events:
       - http:
          path: /productos/categorias/listar
          method: get
          cors: true  

  crearCategoria:
    handler: create_category.lambda_handler
    package:
      include:
        - create_category.py
    events:
      - http:
          path: /categorias/crear
          method: post
          cors: true

  eliminarCategoria:
    handler: delete_category.lambda_handler
    package:
      include:
        - delete_category.py
    events:
      - http:
          path: /categorias/eliminar
          method: delete
          cors: true

  modificarCategoria:
    handler: update_category.lambda_handler
    package:
      include:
        - update_category.py
    events:
      - http:
          path: /categorias/modificar
          method: put
          cors: true

  listarCategorias:
    handler: list_categories.lambda_handler
    package:
      include:
        - list_categories.py
    events:
      - http:
          path: /categorias/listar
          method: get
          cors: true

resources:
  Resources:
    ProductosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: id_producto
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: id_producto
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    CategoriasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CATEGORIES_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: id_categoria_producto
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: id_categoria_producto
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
